### ISSUE TITLE
Error When Scanning Physical Items into Department After December: 'Failed to Scan In Item'

### ISSUE THREAD

**Issue by tvcy3016** [ExLibrisGroup/Cloud-app-multi-scan-in#15] opened 2024-12-02 03:55 UTC
Recently, while using the app, I set the Library to Institution Level, and for the Department and Work order type, I selected the department where I wanted the book to be scanned. The only option available was 'Done'. In November, the scanning into the department worked fine, but since December, it always shows: barcode: XXXX info: failed to scan in item. error details: {0}.

**Comment by enettifee** [comment] 2024-12-02 21:05
We're seeing this same issue with some sets of transactions, though not all, at Duke, since the December release yesterday.

**Comment by Dioscorides** [comment] 2024-12-04 09:03
Leiden University sees the same error. We also have ticket open in the support portal.

**Comment by ori229** [comment] 2024-12-04 11:25
See https://developers.exlibrisgroup.com/forums/topic/scan-in-api-raises-errors/
Thanks for bringing this up here. Indeed it's an error caused by a change in Alma's Dec Release.
I'll Close the issue here (since it's a bug in the API and not in the Cloud App).

**Closed by ori229** 2024-12-04 11:25 UTC
